- src/components/lessons/garden-beds/BedLength.vue
- src/components/lessons/garden-beds/Challenge.vue
- src/components/lessons/garden-beds/ExpertChallenge.vue
- src/components/lessons/garden-beds/GardenBed.vue
- src/components/lessons/garden-beds/README.md
- src/components/lessons/garden-beds/utils.js
The testing feedback obtained from Mary, was applied to the garden-bed lesson for all the 4 modules.
- **Demo game**: 
-The difficulty level is high (more likely is expert level). Please make it simple. The plant should be ranged from 1 to 10 (8 is maximum in the original software)
- **Enter your own bed length**: This only have ‘demo’ function. 
-The start button is not same with other lessons. You can have a look on the “Make a million’ lesson for more details
-Required ‘Auto’ function
-When clicking on the ‘Reset’ button, the system does not clear the current game and the graphic. ----User is unable to start new game
-Please put a warning ‘Enter the number of plants (1-50)’ visble above the ’Start’ button to warn teachers and students about the maximum number. 
- **Challenge**
-After …
> Applied Feedback

- src/components/lessons/garden-beds/BedLength.vue
- src/components/lessons/garden-beds/Challenge.vue
- src/components/lessons/garden-beds/ExpertChallenge.vue
- src/components/lessons/garden-beds/utils.js
Fixed the bugs for the 3 of the modules, square being drawn, changed CSS for buttons and radio inputs.
> garden-beds bug fixes

- src/components/lessons/garden-beds/BedLength.vue
- src/components/lessons/garden-beds/Challenge.vue
- src/components/lessons/garden-beds/ExpertChallenge.vue
Finished fixing the timer requirements for the last 3 modules of garden beds which used a timer as specified by Testing team (Mary).
> Timer requirements for Garden beds lesson

- src/components/Home.vue
- src/components/lessons/garden-beds/README.md
- src/components/lessons/same-or-different/App.vue
- src/components/lessons/same-or-different/ManyTrials.vue
- src/components/lessons/same-or-different/PlayAGame.vue
- src/components/lessons/same-or-different/README.md
- src/components/lessons/same-or-different/utils.js
- src/router.js
This lesson is developed based on the original set of lessons provided by the desktop application. (i.e. not from Wie's platform).
There are two different modules for this lesson; 'Play a game' and 'Many trials'.
The formatting and functionality are based on the original software, therefore should be too many differences, but please let me know if there are still bugs which need to be fixed.
> 'Same or different' Lesson Completed

- src/components/Home.vue
- src/components/lessons/number-charts/App.vue
- src/components/lessons/number-charts/FractionAddition.vue
- src/components/lessons/number-charts/WholeNumberAddition.vue
- src/router.js
New lesson
Name: Number Charts
> Upload new lesson of Number Charts

- src/components/Home.vue
- src/components/lessons/goldbachs-conjecture/AListofPrimes.vue
- src/components/lessons/goldbachs-conjecture/App.vue
- src/components/lessons/goldbachs-conjecture/DemoAutoOption.vue
- src/components/lessons/goldbachs-conjecture/EnterYourNumber.vue
- src/components/lessons/goldbachs-conjecture/SearchRange.vue
- src/components/lessons/goldbachs-conjecture/utils.js
- src/router.js
Add lesson - Goldbach's Conjecture
> Add lesson - Goldbach's Conjecture

- package-lock.json
- package.json
- src/components/Home.vue
- src/components/lessons/algebra-charts/Addition.vue
- src/components/lessons/algebra-charts/App.vue
- src/components/lessons/algebra-charts/HighchartsComponent.vue
- src/components/lessons/algebra-charts/Multiplication.vue
- src/components/lessons/algebra-charts/bardemo.vue
- src/router.js
> New lesson Algebra charts

- src/components/Home.vue
- src/components/lessons/fraction-charts/App.vue
- src/components/lessons/fraction-charts/ThreeByThree.vue
- src/components/lessons/fraction-charts/TwoByTwo.vue
- src/router.js
Push a new lesson called Fraction charts
> Push a new lesson called Fraction charts

- src/components/Home.vue
- src/components/lessons/charts-strategies/Addition.vue
- src/components/lessons/charts-strategies/App.vue
- src/components/lessons/charts-strategies/Multiplication.vue
- src/router.js
Pull new lesson named Charts Strategies
> Pull new lesson named Charts Strategies

- src/components/lessons/game-show/FastGame.vue
> Bugs fixed - Show Game

- package-lock.json
- src/components/lessons/fraction-charts/ThreeByThree.vue
- src/components/lessons/fraction-charts/TwoByTwo.vue
Fixed bugs of the lesson called Fraction charts
Henry
> Fractions charts

- src/components/lessons/cylinder-volumes/FindMaximum.vue
- src/components/lessons/cylinder-volumes/InputPanel.vue
- src/components/lessons/cylinder-volumes/TallSquatCylinders.vue
- src/components/lessons/cylinder-volumes/utils.js
Fixed errors listed in spreadsheet for this lesson.
> cylinder volumes: fix spelling & layout issues

- src/components/Home.vue
- src/components/lessons/trigonometry/AngleFromRatio.vue
- src/components/lessons/trigonometry/RadianPlay.vue
- src/components/lessons/trigonometry/RatioFromAngle.vue
- src/components/lessons/trigonometry/utils.js
Fixed all issues on spreadsheet for lessons. As there were lots of changes, I tested quite extensively.
> trig walk: fix canvas issues etc.

- src/components/lessons/truth-tiles-2/ChangeNumbers.vue
- src/components/lessons/truth-tiles-2/Puzzle2.vue
- src/components/lessons/truth-tiles-2/TestingAll.vue
- src/components/lessons/truth-tiles-2/TestingStrategies.vue
Most bugs from the spreadsheet fixed, including the really nasty intermittent one causing random numbers to show up in calculations. Phew!
> truth tiles 2: fix bugs

- src/components/lessons/2-litre-ballon/DisplayData.vue
- src/components/lessons/2-litre-ballon/EnterData.vue
Fixed all issues in the spreadsheet.
Note: I have changed the way the program functions from the original PC/Mac software as it was confusing and not in line with the lesson.
> 2 litre balloon: add functionality and change layout

- src/components/lessons/counter-escape/PlayGame.vue
Minor changes, but my editor must like removing trailing whitespace!
> counter escape: make small improvements

- src/components/lessons/sporting-finals-AFL/App.vue
- src/components/lessons/sporting-finals-AFL/PlayFinals.vue
- src/components/lessons/sporting-finals-NRL/App.vue
- src/components/lessons/sporting-finals-NRL/PlayFinals.vue
> sporting finals: update dice on both lessons

- src/components/lessons/crosses/TestingAll.vue
> crosses: add instructions

- src/components/lessons/addo/HowOften.vue
- src/components/lessons/addo/ManyGamesApp.vue
- src/components/lessons/addo/ManyGamesStat.vue
- src/components/lessons/addo/OneGame.vue
- src/components/lessons/addo/utils/utils.js
- src/components/lessons/multo/HowOften.vue
- src/components/lessons/multo/ManyGamesApp.vue
- src/components/lessons/multo/ManyGamesStat.vue
- src/components/lessons/multo/OneGame.vue
- src/components/lessons/multo/utils/utils.js
Includes: 
- labels to make things clearer
- dealing with draws in a more systematic (and transparent) way
- generating a deck of "cards" to ensure no repeats during a game
etc.
> more work on addo & multo

- src/components/lessons/knight-tour/ExploreStrategiesApp.vue
- src/components/lessons/knight-tour/ManyTrialsApp.vue
- src/components/lessons/knight-tour/PlayGame.vue
- src/components/lessons/knight-tour/SelectingStrategy.vue
- src/components/lessons/knight-tour/TourStatSeparate.vue
- src/components/lessons/knight-tour/TourStatTotal.vue
I have made some usability and presentation improvements. The original software was confusing in parts, hopefully this will help and be more in line with the lesson plan.
> Lesson fixes

- src/components/lessons/algebra-charts/Addition.vue
- src/components/lessons/algebra-charts/Multiplication.vue
- src/components/lessons/charts-strategies/Addition.vue
- src/components/lessons/charts-strategies/Multiplication.vue
- src/components/lessons/number-charts/FractionAddition.vue
- src/components/lessons/number-charts/WholeNumberAddition.vue
Fixed errors in three lessons
algebra charts
chart strategies
number charts
> [Fixed Bugs] Error Message Display Issue
